
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_project
    username: root
    password: 123456


mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.cqu.student.pojo
  configuration:
    map-underscore-to-camel-case: on

files:
  upload:
    path: 'D:\talent\files\' # 文件上传路径
    fileMapper: '/profile/' # 文件映射路径

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl